library(wordcloud)
library(rJava)
library(KoNLP)
library(RColorBrewer)
setwd('/home/parallels/cnu_datascience/week7')
txt <- readLines("data.txt")
naver <- sapply(txt, extractNoun, USE.NAMES = F)
head(unlist(naver), 30)
c <- unlist(naver)
naver_list <- Filter(function(x){nchar(x) >= 2}, c)
wordcount <- table(pledge_list)
head(sort(wordcount, decreasing=T),30)
palete <- brewer.pal(9,"Set1")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,1),rot.per=0.25, min.freq=1, random.order=F,random.colors=T,colors=palete)
savePlot("naver_news.png",type="png")
