library(ggplot2)
library(extrafont)
library(sqldf)
font_import("AppleMyungjo")
station = read.csv("station.csv", sep= ',')
station_area  <- sqldf("select 구별, count(*) as count from station group by 구별")
print(station_area)
g <- ggplot(station, aes(x=구별))
b <- geom_bar(fill='black', color ="black")
g+ b + theme(text=element_text(family = "AppleMyungjo"))