library(wordcloud)
library(rJava)
library(KoNLP)
library(RColorBrewer)
setwd('/home/parallels/cnu_datascience/week5')
txt <- readLines("pledges.txt")
pledge <- sapply(txt, extractNoun, USE.NAMES = F)
head(unlist(pledge), 30)
c <- unlist(pledge)
# 선거 공약 데이터를 가져와 적당히 후처리 후 워드클라우딩을 한다
pledge_list <- Filter(function(x){nchar(x) >= 2}, c)
pledge_list <- gsub("\\d+",pledge_list)
pledge_list <- gsub("공약",pledge_list)
wordcount <- table(pledge_list)
head(sort(wordcount, decreasing=T),30)
palete <- brewer.pal(9,"Set1")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,1),rot.per=0.25, min.freq=1, random.order=F,random.colors=T,colors=palete)
savePlot("pledge.png",type="png")