library(wordcloud)
library(rJava)
library(KoNLP)
library(RColorBrewer)
setwd('/home/parallels/cnu_datascience/week5')
txt <- readLines("pledges.txt")
pledge <- sapply(txt, extractNoun, USE.NAMES = F)
head(unlist(pledge), 30)
c <- unlist(pledge)
place <- Filter(function(x){nchar(x) >= 2}, c)
write(unlist(pledge),"pledge_2.txt")
rev <- read.table("pledge_2.txt", header= FALSE)
rev
wordcount <- table(rev)
head(sort(wordcount, decreasing=T),30)
palete <- brewer.pal(9,"Set1")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,1),rot.per=0.25, min.freq=1, random.order=F,random.colors=T,colors=palete)
savePlot("pledge.png",type="png")