library(wordcloud)
library(rJava)
library(KoNLP)
library(RColorBrewer)
setwd('/Users/corona10/cnu_datascience/week5')
txt <- readLines("jeju.txt")
place <- sapply(txt, extractNoun, USE.NAMES = F)
head(unlist(place), 30)
c <- unlist(place)
place <- Filter(function(x){nchar(x) >= 2}, c)
write(unlist(place),"jeju_2.txt")